# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5885c7b14b5a2b5fc49683fac0ab0b8887b0f12507d5025edd394dda98b48db8773f68b8ec1b83cc90c5f322030aa98aef9785ca91bdc0d70c1817728c02c88

test:
  secret_key_base: 17381639628264037489e08cc268cc6be47b4578400a93fad9fa37635b09fca2ae15dfe1acb9908c46e18959ff0e561c2059e1f17c4e7ab3e3207ae7c89a42fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
